name: Bug Report🐛
description: File a bug report
title: "[BUG]: "
labels: ["bug"]
# projects: []
# assignees: ["vihar-s1"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!🤗

  - type: textarea
    id: bug-description
    attributes:
      label: Brief Bug Description
      description: Tell us about what happened? |
        Use Screenshots where necessary to assist explanation.
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Brief Idea about Expected Behavior
      description: Tell us about what did you expect to happen? |
        Use Screenshots where necessary to assist explanation.
      placeholder: Tell us what you want to see!
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell

  - type: checkboxes
    id: checks
    attributes:
      label: Check-List
      description: Please make sure to check the following milestones before submitting the bug report!
      options:
        - label: I have checked that a similar kind of bug report does not already exist!
          required: true
        - label: I can reproduce the issue consistently.
          required: true
        - label: I have read the [Contributing Guidelines](https://github.com/vihar-s1/Ciphers/blob/main/CONTRIBUTING.md)
          required: true
        - label: I want to work on solving the bug !